/*flexberryautogenerated="true"*/
namespace IIS.Bakery
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class DefectedCakeL : BaseListForm<DefectedCake>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public DefectedCakeL() : base(DefectedCake.Views.DefectedCakeL)
        {
            EditPage = DefectedCakeE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/DefectedCake/DefectedCakeL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
