//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Bakery
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Cake to sale.
    /// </summary>
    // *** Start programmer edit section *** (CakeToSale CustomAttributes)

    // *** End programmer edit section *** (CakeToSale CustomAttributes)
    [BusinessServer("IIS.Bakery.CakeToSaleBS, Bakery.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [Caption("Cake to sale")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Bakery_CakeToSaleE", new string[] {
            "Name as \'Name\'",
            "FabricationDate as \'Fabrication date\'",
            "Count as \'Count\'",
            "Baker as \'Baker\'",
            "Baker.Personalkey as \'Personalkey\'",
            "Cake as \'Cake\'",
            "Cake.Name as \'Name\'"})]
    [View("Bakery_CakeToSaleL", new string[] {
            "Name as \'Name\'",
            "FabricationDate as \'Fabrication date\'",
            "Count as \'Count\'",
            "Baker.Personalkey as \'Personalkey\'",
            "Cake.Name as \'Name\'"})]
    [View("CakeToSaleE", new string[] {
            "Name as \'Name\'",
            "FabricationDate as \'Fabrication date\'",
            "Count as \'Count\'",
            "Baker as \'Baker\'",
            "Baker.Personalkey as \'Personalkey\'",
            "Cake as \'Cake\'",
            "Cake.Name as \'Name\'"})]
    [View("CakeToSaleL", new string[] {
            "Name as \'Name\'",
            "FabricationDate as \'Fabrication date\'",
            "Count as \'Count\'",
            "Baker.Personalkey as \'Personalkey\'",
            "Cake.Name as \'Name\'"})]
    public class CakeToSale : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private System.DateTime fFabricationDate;
        
        private int fCount;
        
        private IIS.Bakery.Staff fBaker;
        
        private IIS.Bakery.Cake fCake;
        
        // *** Start programmer edit section *** (CakeToSale CustomMembers)

        // *** End programmer edit section *** (CakeToSale CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (CakeToSale.Name CustomAttributes)

        // *** End programmer edit section *** (CakeToSale.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (CakeToSale.Name Get start)

                // *** End programmer edit section *** (CakeToSale.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (CakeToSale.Name Get end)

                // *** End programmer edit section *** (CakeToSale.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CakeToSale.Name Set start)

                // *** End programmer edit section *** (CakeToSale.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (CakeToSale.Name Set end)

                // *** End programmer edit section *** (CakeToSale.Name Set end)
            }
        }
        
        /// <summary>
        /// FabricationDate.
        /// </summary>
        // *** Start programmer edit section *** (CakeToSale.FabricationDate CustomAttributes)

        // *** End programmer edit section *** (CakeToSale.FabricationDate CustomAttributes)
        public virtual System.DateTime FabricationDate
        {
            get
            {
                // *** Start programmer edit section *** (CakeToSale.FabricationDate Get start)

                // *** End programmer edit section *** (CakeToSale.FabricationDate Get start)
                System.DateTime result = this.fFabricationDate;
                // *** Start programmer edit section *** (CakeToSale.FabricationDate Get end)

                // *** End programmer edit section *** (CakeToSale.FabricationDate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CakeToSale.FabricationDate Set start)

                // *** End programmer edit section *** (CakeToSale.FabricationDate Set start)
                this.fFabricationDate = value;
                // *** Start programmer edit section *** (CakeToSale.FabricationDate Set end)

                // *** End programmer edit section *** (CakeToSale.FabricationDate Set end)
            }
        }
        
        /// <summary>
        /// Count.
        /// </summary>
        // *** Start programmer edit section *** (CakeToSale.Count CustomAttributes)

        // *** End programmer edit section *** (CakeToSale.Count CustomAttributes)
        public virtual int Count
        {
            get
            {
                // *** Start programmer edit section *** (CakeToSale.Count Get start)

                // *** End programmer edit section *** (CakeToSale.Count Get start)
                int result = this.fCount;
                // *** Start programmer edit section *** (CakeToSale.Count Get end)

                // *** End programmer edit section *** (CakeToSale.Count Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CakeToSale.Count Set start)

                // *** End programmer edit section *** (CakeToSale.Count Set start)
                this.fCount = value;
                // *** Start programmer edit section *** (CakeToSale.Count Set end)

                // *** End programmer edit section *** (CakeToSale.Count Set end)
            }
        }
        
        /// <summary>
        /// Cake to sale.
        /// </summary>
        // *** Start programmer edit section *** (CakeToSale.Baker CustomAttributes)

        // *** End programmer edit section *** (CakeToSale.Baker CustomAttributes)
        [NotNull()]
        public virtual IIS.Bakery.Staff Baker
        {
            get
            {
                // *** Start programmer edit section *** (CakeToSale.Baker Get start)

                // *** End programmer edit section *** (CakeToSale.Baker Get start)
                IIS.Bakery.Staff result = this.fBaker;
                // *** Start programmer edit section *** (CakeToSale.Baker Get end)

                // *** End programmer edit section *** (CakeToSale.Baker Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CakeToSale.Baker Set start)

                // *** End programmer edit section *** (CakeToSale.Baker Set start)
                this.fBaker = value;
                // *** Start programmer edit section *** (CakeToSale.Baker Set end)

                // *** End programmer edit section *** (CakeToSale.Baker Set end)
            }
        }
        
        /// <summary>
        /// Cake to sale.
        /// </summary>
        // *** Start programmer edit section *** (CakeToSale.Cake CustomAttributes)

        // *** End programmer edit section *** (CakeToSale.Cake CustomAttributes)
        [NotNull()]
        public virtual IIS.Bakery.Cake Cake
        {
            get
            {
                // *** Start programmer edit section *** (CakeToSale.Cake Get start)

                // *** End programmer edit section *** (CakeToSale.Cake Get start)
                IIS.Bakery.Cake result = this.fCake;
                // *** Start programmer edit section *** (CakeToSale.Cake Get end)

                // *** End programmer edit section *** (CakeToSale.Cake Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CakeToSale.Cake Set start)

                // *** End programmer edit section *** (CakeToSale.Cake Set start)
                this.fCake = value;
                // *** Start programmer edit section *** (CakeToSale.Cake Set end)

                // *** End programmer edit section *** (CakeToSale.Cake Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Bakery_CakeToSaleE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Bakery_CakeToSaleE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Bakery_CakeToSaleE", typeof(IIS.Bakery.CakeToSale));
                }
            }
            
            /// <summary>
            /// "Bakery_CakeToSaleL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Bakery_CakeToSaleL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Bakery_CakeToSaleL", typeof(IIS.Bakery.CakeToSale));
                }
            }
            
            /// <summary>
            /// "CakeToSaleE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CakeToSaleE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CakeToSaleE", typeof(IIS.Bakery.CakeToSale));
                }
            }
            
            /// <summary>
            /// "CakeToSaleL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CakeToSaleL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CakeToSaleL", typeof(IIS.Bakery.CakeToSale));
                }
            }
        }
    }
}
