//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Bakery
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Cake.
    /// </summary>
    // *** Start programmer edit section *** (Cake CustomAttributes)

    // *** End programmer edit section *** (Cake CustomAttributes)
    [BusinessServer("IIS.Bakery.CakeBS, Bakery.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Bakery_CakeE", new string[] {
            "Name as \'Name\'",
            "Lifetime as \'Lifetime\'",
            "Imagelink as \'Imagelink\'",
            "Price as \'Price\'",
            "Actual as \'Actual\'"})]
    [View("Bakery_CakeL", new string[] {
            "Name as \'Name\'",
            "Lifetime as \'Lifetime\'",
            "Imagelink as \'Imagelink\'",
            "Price as \'Price\'",
            "Actual as \'Actual\'"})]
    [View("CakeE", new string[] {
            "Name as \'Name\'",
            "Lifetime as \'Lifetime\'",
            "Imagelink as \'Imagelink\'",
            "Price as \'Price\'",
            "Actual as \'Actual\'"})]
    [View("CakeL", new string[] {
            "Name as \'Name\'",
            "Lifetime as \'Lifetime\'",
            "Imagelink as \'Imagelink\'",
            "Price as \'Price\'",
            "Actual as \'Actual\'"})]
    public class Cake : ICSSoft.STORMNET.DataObject, IIS.Bakery.MyDicttionary
    {
        
        private string fName;
        
        private int fLifetime;
        
        private string fImagelink;
        
        private decimal fPrice;
        
        private bool fActual = true;
        
        // *** Start programmer edit section *** (Cake CustomMembers)

        // *** End programmer edit section *** (Cake CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Cake.Name CustomAttributes)

        // *** End programmer edit section *** (Cake.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Cake.Name Get start)

                // *** End programmer edit section *** (Cake.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Cake.Name Get end)

                // *** End programmer edit section *** (Cake.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Cake.Name Set start)

                // *** End programmer edit section *** (Cake.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Cake.Name Set end)

                // *** End programmer edit section *** (Cake.Name Set end)
            }
        }
        
        /// <summary>
        /// Lifetime.
        /// </summary>
        // *** Start programmer edit section *** (Cake.Lifetime CustomAttributes)

        // *** End programmer edit section *** (Cake.Lifetime CustomAttributes)
        public virtual int Lifetime
        {
            get
            {
                // *** Start programmer edit section *** (Cake.Lifetime Get start)

                // *** End programmer edit section *** (Cake.Lifetime Get start)
                int result = this.fLifetime;
                // *** Start programmer edit section *** (Cake.Lifetime Get end)

                // *** End programmer edit section *** (Cake.Lifetime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Cake.Lifetime Set start)

                // *** End programmer edit section *** (Cake.Lifetime Set start)
                this.fLifetime = value;
                // *** Start programmer edit section *** (Cake.Lifetime Set end)

                // *** End programmer edit section *** (Cake.Lifetime Set end)
            }
        }
        
        /// <summary>
        /// Imagelink.
        /// </summary>
        // *** Start programmer edit section *** (Cake.Imagelink CustomAttributes)

        // *** End programmer edit section *** (Cake.Imagelink CustomAttributes)
        [StrLen(255)]
        public virtual string Imagelink
        {
            get
            {
                // *** Start programmer edit section *** (Cake.Imagelink Get start)

                // *** End programmer edit section *** (Cake.Imagelink Get start)
                string result = this.fImagelink;
                // *** Start programmer edit section *** (Cake.Imagelink Get end)

                // *** End programmer edit section *** (Cake.Imagelink Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Cake.Imagelink Set start)

                // *** End programmer edit section *** (Cake.Imagelink Set start)
                this.fImagelink = value;
                // *** Start programmer edit section *** (Cake.Imagelink Set end)

                // *** End programmer edit section *** (Cake.Imagelink Set end)
            }
        }
        
        /// <summary>
        /// Price.
        /// </summary>
        // *** Start programmer edit section *** (Cake.Price CustomAttributes)

        // *** End programmer edit section *** (Cake.Price CustomAttributes)
        public virtual decimal Price
        {
            get
            {
                // *** Start programmer edit section *** (Cake.Price Get start)

                // *** End programmer edit section *** (Cake.Price Get start)
                decimal result = this.fPrice;
                // *** Start programmer edit section *** (Cake.Price Get end)

                // *** End programmer edit section *** (Cake.Price Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Cake.Price Set start)

                // *** End programmer edit section *** (Cake.Price Set start)
                this.fPrice = value;
                // *** Start programmer edit section *** (Cake.Price Set end)

                // *** End programmer edit section *** (Cake.Price Set end)
            }
        }
        
        /// <summary>
        /// Actual.
        /// </summary>
        // *** Start programmer edit section *** (Cake.Actual CustomAttributes)

        // *** End programmer edit section *** (Cake.Actual CustomAttributes)
        public virtual bool Actual
        {
            get
            {
                // *** Start programmer edit section *** (Cake.Actual Get start)

                // *** End programmer edit section *** (Cake.Actual Get start)
                bool result = this.fActual;
                // *** Start programmer edit section *** (Cake.Actual Get end)

                // *** End programmer edit section *** (Cake.Actual Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Cake.Actual Set start)

                // *** End programmer edit section *** (Cake.Actual Set start)
                this.fActual = value;
                // *** Start programmer edit section *** (Cake.Actual Set end)

                // *** End programmer edit section *** (Cake.Actual Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Bakery_CakeE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Bakery_CakeE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Bakery_CakeE", typeof(IIS.Bakery.Cake));
                }
            }
            
            /// <summary>
            /// "Bakery_CakeL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Bakery_CakeL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Bakery_CakeL", typeof(IIS.Bakery.Cake));
                }
            }
            
            /// <summary>
            /// "CakeE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CakeE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CakeE", typeof(IIS.Bakery.Cake));
                }
            }
            
            /// <summary>
            /// "CakeL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CakeL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CakeL", typeof(IIS.Bakery.Cake));
                }
            }
        }
    }
}
