//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Bakery
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// My dicttionary.
    /// </summary>
    // *** Start programmer edit section *** (MyDicttionary CustomAttributes)

    // *** End programmer edit section *** (MyDicttionary CustomAttributes)
    public interface MyDicttionary
    {
        
        // *** Start programmer edit section *** (MyDicttionary CustomMembers)

        // *** End programmer edit section *** (MyDicttionary CustomMembers)

        
        /// <summary>
        /// Actual.
        /// </summary>
        // *** Start programmer edit section *** (Actual CustomAttributes)

        // *** End programmer edit section *** (Actual CustomAttributes)
        bool Actual
        {
            get;
            set;
        }
    }
}
