//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Bakery
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Request status.
    /// </summary>
    // *** Start programmer edit section *** (RequestStatus CustomAttributes)

    // *** End programmer edit section *** (RequestStatus CustomAttributes)
    public enum RequestStatus
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (RequestStatus.Created CustomAttributes)

        // *** End programmer edit section *** (RequestStatus.Created CustomAttributes)
        Created,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (RequestStatus.Paid CustomAttributes)

        // *** End programmer edit section *** (RequestStatus.Paid CustomAttributes)
        Paid,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (RequestStatus.Decilned CustomAttributes)

        // *** End programmer edit section *** (RequestStatus.Decilned CustomAttributes)
        Decilned,
    }
}
