//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Bakery
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Shift.
    /// </summary>
    // *** Start programmer edit section *** (Shift CustomAttributes)

    // *** End programmer edit section *** (Shift CustomAttributes)
    [BusinessServer("IIS.Bakery.ShiftBS, Bakery.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Bakery_ShiftE", new string[] {
            "Start as \'Start\'",
            "End as \'End\'",
            "Status as \'Status\'",
            "Cash as \'Cash\'",
            "InterruptReason as \'Interrupt reason\'",
            "Cashier as \'Cashier\'",
            "Cashier.Personalkey as \'Personalkey\'"})]
    [View("Bakery_ShiftL", new string[] {
            "Start as \'Start\'",
            "End as \'End\'",
            "Status as \'Status\'",
            "Cash as \'Cash\'",
            "InterruptReason as \'Interrupt reason\'",
            "Cashier.Personalkey as \'Personalkey\'"})]
    [View("ShiftE", new string[] {
            "Start as \'Start\'",
            "End as \'End\'",
            "Status as \'Status\'",
            "Cash as \'Cash\'",
            "InterruptReason as \'Interrupt reason\'",
            "Cashier as \'Cashier\'",
            "Cashier.Personalkey as \'Personalkey\'"})]
    [View("ShiftL", new string[] {
            "Start as \'Start\'",
            "End as \'End\'",
            "Status as \'Status\'",
            "Cash as \'Cash\'",
            "InterruptReason as \'Interrupt reason\'",
            "Cashier.Personalkey as \'Personalkey\'"})]
    public class Shift : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fStart;
        
        private System.DateTime fEnd;
        
        private IIS.Bakery.ShiftStatus fStatus;
        
        private string fInterruptReason;
        
        private IIS.Bakery.Staff fCashier;
        
        // *** Start programmer edit section *** (Shift CustomMembers)

        // *** End programmer edit section *** (Shift CustomMembers)

        
        /// <summary>
        /// Start.
        /// </summary>
        // *** Start programmer edit section *** (Shift.Start CustomAttributes)

        // *** End programmer edit section *** (Shift.Start CustomAttributes)
        public virtual System.DateTime Start
        {
            get
            {
                // *** Start programmer edit section *** (Shift.Start Get start)

                // *** End programmer edit section *** (Shift.Start Get start)
                System.DateTime result = this.fStart;
                // *** Start programmer edit section *** (Shift.Start Get end)

                // *** End programmer edit section *** (Shift.Start Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Shift.Start Set start)

                // *** End programmer edit section *** (Shift.Start Set start)
                this.fStart = value;
                // *** Start programmer edit section *** (Shift.Start Set end)

                // *** End programmer edit section *** (Shift.Start Set end)
            }
        }
        
        /// <summary>
        /// End.
        /// </summary>
        // *** Start programmer edit section *** (Shift.End CustomAttributes)

        // *** End programmer edit section *** (Shift.End CustomAttributes)
        public virtual System.DateTime End
        {
            get
            {
                // *** Start programmer edit section *** (Shift.End Get start)

                // *** End programmer edit section *** (Shift.End Get start)
                System.DateTime result = this.fEnd;
                // *** Start programmer edit section *** (Shift.End Get end)

                // *** End programmer edit section *** (Shift.End Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Shift.End Set start)

                // *** End programmer edit section *** (Shift.End Set start)
                this.fEnd = value;
                // *** Start programmer edit section *** (Shift.End Set end)

                // *** End programmer edit section *** (Shift.End Set end)
            }
        }
        
        /// <summary>
        /// Status.
        /// </summary>
        // *** Start programmer edit section *** (Shift.Status CustomAttributes)

        // *** End programmer edit section *** (Shift.Status CustomAttributes)
        public virtual IIS.Bakery.ShiftStatus Status
        {
            get
            {
                // *** Start programmer edit section *** (Shift.Status Get start)

                // *** End programmer edit section *** (Shift.Status Get start)
                IIS.Bakery.ShiftStatus result = this.fStatus;
                // *** Start programmer edit section *** (Shift.Status Get end)

                // *** End programmer edit section *** (Shift.Status Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Shift.Status Set start)

                // *** End programmer edit section *** (Shift.Status Set start)
                this.fStatus = value;
                // *** Start programmer edit section *** (Shift.Status Set end)

                // *** End programmer edit section *** (Shift.Status Set end)
            }
        }
        
        /// <summary>
        /// Cash.
        /// </summary>
        // *** Start programmer edit section *** (Shift.Cash CustomAttributes)

        // *** End programmer edit section *** (Shift.Cash CustomAttributes)
        [ICSSoft.STORMNET.NotStored()]
        public virtual decimal Cash
        {
            get
            {
                // *** Start programmer edit section *** (Shift.Cash Get)

                return 0;
                // *** End programmer edit section *** (Shift.Cash Get)
            }
            set
            {
                // *** Start programmer edit section *** (Shift.Cash Set)

                // *** End programmer edit section *** (Shift.Cash Set)
            }
        }
        
        /// <summary>
        /// InterruptReason.
        /// </summary>
        // *** Start programmer edit section *** (Shift.InterruptReason CustomAttributes)

        // *** End programmer edit section *** (Shift.InterruptReason CustomAttributes)
        [StrLen(255)]
        public virtual string InterruptReason
        {
            get
            {
                // *** Start programmer edit section *** (Shift.InterruptReason Get start)

                // *** End programmer edit section *** (Shift.InterruptReason Get start)
                string result = this.fInterruptReason;
                // *** Start programmer edit section *** (Shift.InterruptReason Get end)

                // *** End programmer edit section *** (Shift.InterruptReason Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Shift.InterruptReason Set start)

                // *** End programmer edit section *** (Shift.InterruptReason Set start)
                this.fInterruptReason = value;
                // *** Start programmer edit section *** (Shift.InterruptReason Set end)

                // *** End programmer edit section *** (Shift.InterruptReason Set end)
            }
        }
        
        /// <summary>
        /// Shift.
        /// </summary>
        // *** Start programmer edit section *** (Shift.Cashier CustomAttributes)

        // *** End programmer edit section *** (Shift.Cashier CustomAttributes)
        [NotNull()]
        public virtual IIS.Bakery.Staff Cashier
        {
            get
            {
                // *** Start programmer edit section *** (Shift.Cashier Get start)

                // *** End programmer edit section *** (Shift.Cashier Get start)
                IIS.Bakery.Staff result = this.fCashier;
                // *** Start programmer edit section *** (Shift.Cashier Get end)

                // *** End programmer edit section *** (Shift.Cashier Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Shift.Cashier Set start)

                // *** End programmer edit section *** (Shift.Cashier Set start)
                this.fCashier = value;
                // *** Start programmer edit section *** (Shift.Cashier Set end)

                // *** End programmer edit section *** (Shift.Cashier Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Bakery_ShiftE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Bakery_ShiftE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Bakery_ShiftE", typeof(IIS.Bakery.Shift));
                }
            }
            
            /// <summary>
            /// "Bakery_ShiftL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Bakery_ShiftL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Bakery_ShiftL", typeof(IIS.Bakery.Shift));
                }
            }
            
            /// <summary>
            /// "ShiftE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ShiftE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ShiftE", typeof(IIS.Bakery.Shift));
                }
            }
            
            /// <summary>
            /// "ShiftL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ShiftL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ShiftL", typeof(IIS.Bakery.Shift));
                }
            }
        }
    }
}
