//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Bakery
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Shift status.
    /// </summary>
    // *** Start programmer edit section *** (ShiftStatus CustomAttributes)

    // *** End programmer edit section *** (ShiftStatus CustomAttributes)
    public enum ShiftStatus
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (ShiftStatus.Started CustomAttributes)

        // *** End programmer edit section *** (ShiftStatus.Started CustomAttributes)
        Started,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (ShiftStatus.Ended CustomAttributes)

        // *** End programmer edit section *** (ShiftStatus.Ended CustomAttributes)
        Ended,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (ShiftStatus.Interrupted CustomAttributes)

        // *** End programmer edit section *** (ShiftStatus.Interrupted CustomAttributes)
        Interrupted,
    }
}
