//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Bakery
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Staff.
    /// </summary>
    // *** Start programmer edit section *** (Staff CustomAttributes)

    // *** End programmer edit section *** (Staff CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Bakery_StaffE", new string[] {
            "Personalkey as \'Personalkey\'",
            "Name as \'Name\'",
            "Surname as \'Surname\'",
            "Role as \'Role\'",
            "Actual as \'Actual\'"})]
    [View("Bakery_StaffL", new string[] {
            "Personalkey as \'Personalkey\'",
            "Name as \'Name\'",
            "Surname as \'Surname\'",
            "Role as \'Role\'",
            "Actual as \'Actual\'"})]
    [View("StaffE", new string[] {
            "Personalkey as \'Personalkey\'",
            "Name as \'Name\'",
            "Surname as \'Surname\'",
            "Role as \'Role\'",
            "Actual as \'Actual\'"})]
    [View("StaffL", new string[] {
            "Personalkey as \'Personalkey\'",
            "Name as \'Name\'",
            "Surname as \'Surname\'",
            "Role as \'Role\'",
            "Actual as \'Actual\'"})]
    public class Staff : ICSSoft.STORMNET.DataObject, IIS.Bakery.MyDicttionary
    {
        
        private string fPersonalkey;
        
        private string fName;
        
        private string fSurname;
        
        private string fRole;
        
        private bool fActual = true;
        
        // *** Start programmer edit section *** (Staff CustomMembers)

        // *** End programmer edit section *** (Staff CustomMembers)

        
        /// <summary>
        /// Personalkey.
        /// </summary>
        // *** Start programmer edit section *** (Staff.Personalkey CustomAttributes)

        // *** End programmer edit section *** (Staff.Personalkey CustomAttributes)
        [StrLen(255)]
        public virtual string Personalkey
        {
            get
            {
                // *** Start programmer edit section *** (Staff.Personalkey Get start)

                // *** End programmer edit section *** (Staff.Personalkey Get start)
                string result = this.fPersonalkey;
                // *** Start programmer edit section *** (Staff.Personalkey Get end)

                // *** End programmer edit section *** (Staff.Personalkey Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Staff.Personalkey Set start)

                // *** End programmer edit section *** (Staff.Personalkey Set start)
                this.fPersonalkey = value;
                // *** Start programmer edit section *** (Staff.Personalkey Set end)

                // *** End programmer edit section *** (Staff.Personalkey Set end)
            }
        }
        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Staff.Name CustomAttributes)

        // *** End programmer edit section *** (Staff.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Staff.Name Get start)

                // *** End programmer edit section *** (Staff.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Staff.Name Get end)

                // *** End programmer edit section *** (Staff.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Staff.Name Set start)

                // *** End programmer edit section *** (Staff.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Staff.Name Set end)

                // *** End programmer edit section *** (Staff.Name Set end)
            }
        }
        
        /// <summary>
        /// Surname.
        /// </summary>
        // *** Start programmer edit section *** (Staff.Surname CustomAttributes)

        // *** End programmer edit section *** (Staff.Surname CustomAttributes)
        [StrLen(255)]
        public virtual string Surname
        {
            get
            {
                // *** Start programmer edit section *** (Staff.Surname Get start)

                // *** End programmer edit section *** (Staff.Surname Get start)
                string result = this.fSurname;
                // *** Start programmer edit section *** (Staff.Surname Get end)

                // *** End programmer edit section *** (Staff.Surname Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Staff.Surname Set start)

                // *** End programmer edit section *** (Staff.Surname Set start)
                this.fSurname = value;
                // *** Start programmer edit section *** (Staff.Surname Set end)

                // *** End programmer edit section *** (Staff.Surname Set end)
            }
        }
        
        /// <summary>
        /// Role.
        /// </summary>
        // *** Start programmer edit section *** (Staff.Role CustomAttributes)

        // *** End programmer edit section *** (Staff.Role CustomAttributes)
        [StrLen(255)]
        public virtual string Role
        {
            get
            {
                // *** Start programmer edit section *** (Staff.Role Get start)

                // *** End programmer edit section *** (Staff.Role Get start)
                string result = this.fRole;
                // *** Start programmer edit section *** (Staff.Role Get end)

                // *** End programmer edit section *** (Staff.Role Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Staff.Role Set start)

                // *** End programmer edit section *** (Staff.Role Set start)
                this.fRole = value;
                // *** Start programmer edit section *** (Staff.Role Set end)

                // *** End programmer edit section *** (Staff.Role Set end)
            }
        }
        
        /// <summary>
        /// Actual.
        /// </summary>
        // *** Start programmer edit section *** (Staff.Actual CustomAttributes)

        // *** End programmer edit section *** (Staff.Actual CustomAttributes)
        public virtual bool Actual
        {
            get
            {
                // *** Start programmer edit section *** (Staff.Actual Get start)

                // *** End programmer edit section *** (Staff.Actual Get start)
                bool result = this.fActual;
                // *** Start programmer edit section *** (Staff.Actual Get end)

                // *** End programmer edit section *** (Staff.Actual Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Staff.Actual Set start)

                // *** End programmer edit section *** (Staff.Actual Set start)
                this.fActual = value;
                // *** Start programmer edit section *** (Staff.Actual Set end)

                // *** End programmer edit section *** (Staff.Actual Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Bakery_StaffE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Bakery_StaffE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Bakery_StaffE", typeof(IIS.Bakery.Staff));
                }
            }
            
            /// <summary>
            /// "Bakery_StaffL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Bakery_StaffL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Bakery_StaffL", typeof(IIS.Bakery.Staff));
                }
            }
            
            /// <summary>
            /// "StaffE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View StaffE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("StaffE", typeof(IIS.Bakery.Staff));
                }
            }
            
            /// <summary>
            /// "StaffL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View StaffL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("StaffL", typeof(IIS.Bakery.Staff));
                }
            }
        }
    }
}
