//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Bakery
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Cake BS.
    /// </summary>
    // *** Start programmer edit section *** (CakeBS CustomAttributes)

    // *** End programmer edit section *** (CakeBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class CakeBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (CakeBS CustomMembers)

        // *** End programmer edit section *** (CakeBS CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateCake CustomAttributes)

        // *** End programmer edit section *** (OnUpdateCake CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateCake(IIS.Bakery.Cake UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateCake)

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateCake)
        }
    }
}
