//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Bakery
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// CakeToSaleBS.
    /// </summary>
    // *** Start programmer edit section *** (CakeToSaleBS CustomAttributes)

    // *** End programmer edit section *** (CakeToSaleBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class CakeToSaleBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (CakeToSaleBS CustomMembers)

        // *** End programmer edit section *** (CakeToSaleBS CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateCakeToSale CustomAttributes)

        // *** End programmer edit section *** (OnUpdateCakeToSale CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateCakeToSale(IIS.Bakery.CakeToSale UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateCakeToSale)

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateCakeToSale)
        }
    }
}
