//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Bakery
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Deleted cake BS.
    /// </summary>
    // *** Start programmer edit section *** (DeletedCakeBS CustomAttributes)

    // *** End programmer edit section *** (DeletedCakeBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class DeletedCakeBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (DeletedCakeBS CustomMembers)

        // *** End programmer edit section *** (DeletedCakeBS CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateDefectedCake CustomAttributes)

        // *** End programmer edit section *** (OnUpdateDefectedCake CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateDefectedCake(IIS.Bakery.DefectedCake UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateDefectedCake)

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateDefectedCake)
        }
    }
}
