//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Bakery
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Shift BS.
    /// </summary>
    // *** Start programmer edit section *** (ShiftBS CustomAttributes)

    // *** End programmer edit section *** (ShiftBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ShiftBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (ShiftBS CustomMembers)

        // *** End programmer edit section *** (ShiftBS CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateShift CustomAttributes)

        // *** End programmer edit section *** (OnUpdateShift CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateShift(IIS.Bakery.Shift UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateShift)

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateShift)
        }
    }
}
