/*flexberryautogenerated="true"*/
namespace IIS.Bakery
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class CakeL : BaseListForm<Cake>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public CakeL() : base(Cake.Views.CakeL)
        {
            EditPage = CakeE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Cake/CakeL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
